tap "go-task/tap"
tap "homebrew/aliases"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "isen-ng/dotnet-sdk-versions"
tap "omnisharp/omnisharp-roslyn"
tap "wez/wezterm"
# Platform built on V8 to build network applications
brew "node"
# Command-line tool for Apollo GraphQL
brew "apollo-cli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Simple terminal UI for git commands
brew "lazygit"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Highly capable, feature-rich programming language
brew "perl"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: true
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Opinionated Lua code formatter
brew "stylua"
# Version control system designed to be a better CVS
brew "subversion"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Ncurses-based file manager with vi-like keybindings
brew "vifm"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Task runner / simpler Make alternative written in Go
brew "go-task/tap/go-task"
# Free monospaced font with programming ligatures
cask "font-fira-code"
# Typeface made for developers
cask "font-jetbrains-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro-for-powerline"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
